Enfermarias_HMRG = 
SWITCH(
    TRUE(),
    
    'vw_estatistica_mensal'[hil_nmsecao] IN {
        "POSTO ASSISTENCIAL 51",
        "POSTO ASSISTENCIAL 53",
        "POSTO ASSISTENCIAL 52",
        "POSTO ASSISTENCIAL 54",
        "POSTO ASSISTENCIAL 34",
        "POSTO ASSISTENCIAL 35"
    }, "CLÍNICA MÉDICA",
    
    'vw_estatistica_mensal'[hil_nmsecao] IN {
        "POSTO ASSISTENCIAL 44",
        "POSTO ASSISTENCIAL 43",
        "POSTO ASSISTENCIAL 41",
        "POSTO ASSISTENCIAL 42",
        "POSTO ASSISTENCIAL 30",
        "POSTO ASSISTENCIAL 36",
        "POSTO ASSISTENCIAL 31"
    }, "CENTRO DE TERAPIA INTENSIVA",
    
    'vw_estatistica_mensal'[hil_nmsecao] IN {
        "POSTO ASSISTENCIAL 11",
        "POSTO ASSISTENCIAL 12"
    }, "CENTRO CIRÚRGICO",
    
    "OUTRAS ENFERMARIAS"
)
